language: node_js
node_js:
  - lts/*
install:
  - yarn --frozen-lockfile
script:
  - yarn build --base=/vue-web-speech-api
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  # A token generated on GitHub allowing Travis to push code on you repository.
  # Set in the Travis settings page of your repository, as a secure variable.
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
